// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itakyjabhodtewgiaauv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0YWt5amFiaG9kdGV3Z2lhYXV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjUzOTEsImV4cCI6MjA3MjkwMTM5MX0.sVCqMoeVMNlUwcBtzYwAprjNs8LRj1MTRlHbGC4UwRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});